FROM ubuntu:latest

WORKDIR /app

COPY DjangoAPP /app

RUN apt-get update && \
    apt-get install -y python3 python3-pip && \
    pip install django

EXPOSE 8000

CMD ["python3", "manage.py", "runserver", "0.0.0.0:8000"]
