FROM ubuntu:latest

# Set working directory inside container
WORKDIR /app

# Copy only the Django project (mysite folder)
COPY djangoAPP/mysite /app

# Install Python and pip
RUN apt-get update && \
    apt-get install -y python3 python3-pip && \
    pip install django

# Expose Django's default port
EXPOSE 8000

# Run Django server
CMD ["python3", "manage.py", "runserver", "0.0.0.0:8000"]
